### ISSUE TITLE
Unable to install on Arch Linux (needs to be published on Open VSX)

### ISSUE THREAD

**Issue by ocelotsloth** [mhansen/hledger-vscode#22]
Hey there! I'm trying to install your excellent extension and running into a roadblock on Arch Linux. Your extension does not show up in the extension marketplace!

From my research (https://github.com/microsoft/vscode/issues/108147#issuecomment-705510202) it seems like Arch Linux's distribution of VSCode uses the Open VSX marketplace instead of Microsoft's.

If you would consider publishing your extension on Open VSX I would be very greatful! Instructions are available here:

  - https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

Additionally, you can make use of the following Github Action to automatically publish to both Open VSX and the Visual Studio Marketplace. It looks like you are currently experimenting with running your unit tests already, so this may already be in the works.

- https://github.com/HaaLeo/publish-vscode-extension#readme

Thanks!

---

## If you're here from a Google search looking for a workaround...

In the meantime, for anybody else who wants to install this extension on Arch Linux, you can click the "Download Extension" button on the following page to get the `.vsix` file and manually install it.

- https://marketplace.visualstudio.com/items?itemName=mark-hansen.hledger-vscode

**Comment by mhansen** [comment]
OK. Thanks very much for your detailed links, made it kinda easy to do it.

Published here: https://open-vsx.org/extension/mark-hansen/hledger-vscode

**Comment by ocelotsloth** [comment]
Thanks so much!

I noticed that it's failing currently due to duplicate tags.

https://github.com/mhansen/hledger-vscode/blob/a7d9ff30fedf39974b16f0ccb15b7e295467d3bf/.github/workflows/deploy.yml#L1-L5

I think you can change `[push]` to something like this:

```yaml
on:
  push:
    tags:
      - 0.*
      - 1.*
```

And then trigger a deployment with

```shell
git tag 0.5.1
git push origin 0.5.1
```

You may need some glue logic in that workflow to dynamically set the version for the extension registry. I'm not sure how that part of it works.

**Comment by mhansen** [comment]
The registry draws its logic from the package.json version. It’s ok, ill
just update the package.json version whenever i want the push to succeed.
Can’t be bothered adding a tag right now (im just lazy)
