### ISSUE TITLE
Syntax coloring for effective dates

### ISSUE THREAD

**Issue by alensiljak** [mhansen/hledger-vscode#260]
When secondary (or effective) dates are used, the coloring breaks down:

![image](https://user-images.githubusercontent.com/462445/200280919-80c1f128-f991-4f47-b25c-244d59e786ab.png)

**Comment by alensiljak** [comment]
Thanks!

**Comment by mhansen** [comment]
May god have mercy upon my soul for these regular expression crimes... https://github.com/mhansen/hledger-vscode/commit/2b51056438fef81842482bd9bb77d0dd93f61e28#diff-89b42d1b3542ae0696e5a3816ce607372c14d198667fd9ad5fef318867385990R29 :-)

**Comment by alensiljak** [comment]
I didn't dare touch it!

**Comment by mhansen** [comment]
I'm thankful for a test suite that'll hopefully tell me if I screw it up too bad.

Should be released soon in v0.0.10: https://marketplace.visualstudio.com/items?itemName=mark-hansen.hledger-vscode

**Comment by alensiljak** [comment]
You are aware of the saying: "If you have a problem, and you need Regular Expressions to solve it, then you have two problems."

**Comment by alensiljak** [comment]
Still white?
![image](https://user-images.githubusercontent.com/462445/200533110-26ec84c7-4013-43a6-9939-0ba00cab20ba.png)

**Comment by mhansen** [comment]
Can you confirm you've updated to 0.0.10? Can you share the entire transaction too, I can add a test for it.

**Comment by alensiljak** [comment]
Sure.
![image](https://user-images.githubusercontent.com/462445/200537852-c70b4488-9135-43ef-a4cd-41d7c9975956.png)

The transaction is nothing special, really:
```
2022-01-07=2021-12-01 BBN Tax Adjustment
    Expenses:Tax:Withholding:Aus
    Assets:Investments:Aus:Cash USD  0.66 USD
```
I've also checked the regex and the groups seem ok. The tmGrammar docs indicate that having duplicate tokens is fine. I'm sorry I'm of not much help.

**Comment by mhansen** [comment]
Ah, bother. Not as easy to fix as I'd hoped. I probably won't have time to
pursue this one anytime soon sorry

**Comment by alensiljak** [comment]
Understood. I was hoping, too, that the Regex addition was enough.
