### ISSUE TITLE
Syntax highlighting for "revenue" in addition to "income"

### ISSUE THREAD

**Issue by thiemo** [mhansen/hledger-vscode#3]
Currently syntax highlighting seems to be implemented for account names beginning with "income", "assets", "liabilities" etc.

As seen in [this hledger tutorial](https://github.com/simonmichael/hledger/wiki/hledger-accounting-concepts-tutorial), "revenue" is encouraged as an account name instead of "income" (see images)

I propose addition of "revenue" to the set of keywords which are to be highlighted.

<img width="138" alt="bildschirmfoto 2019-01-17 um 12 41 42" src="https://user-images.githubusercontent.com/305926/51316535-40032100-1a55-11e9-9056-636367344a80.png"> no highlighting
<img width="146" alt="bildschirmfoto 2019-01-17 um 12 42 00" src="https://user-images.githubusercontent.com/305926/51316542-4a251f80-1a55-11e9-9e93-98cb19ac98e0.png"> ok highlighting

**Comment by mhansen** [comment]
Fixed in 0.0.6
