### ISSUE TITLE
Generalize account syntax

### ISSUE THREAD

**Issue by levitanong** [mhansen/hledger-vscode#6]
AFAIK hledger (and in general, ledger) allows for arbitrary account names, not just starting with liabilities, assets, etc... So more generalized account highlighting would target the first contiguous strings at most separated by one space (because the delimiter between account and amount is two spaces anyway), after the header of the transaction.

i.e.
```
2020-02-02 Payee blah blah
  this:will:be:an:account  20 USD
  this will also be:an account  30 USD
  so will this  -50 USD
```

**Comment by mhansen** [comment]
Do you have a real example of an account you’re using that doesnt start
with one of the prefixes? All mine have the prefixes and I kinda want to be
told of misspellings by the syntax highlighter... you’re technically
correct of course that all types of names are “valid” according to hledger,
just not according to the laws of accounting.

**Comment by levitanong** [comment]
I have a separate top-level account called `obligations`, which helps me keep track of me and my friends owing money to each other. 

Formal accounting rules are too cumbersome for this task: if I owe someone money, it's a `liability`, but if they owe me it's an `asset:receivable`. Checking the balance between me and my friends requires me to check two different accounts.

This separate `obligations` account allows me to just consolidate everything. If it's negative, I owe them. If it's positive, they owe me.

I get the desire for syntax highlighting to aid in spell checking, but IMHO that's sort of overloading the function of syntax highlighting. I think spell checking is better served by autocompletion (which it seems is on the roadmap) and explicit account declarations like so: https://hledger.org/journal.html#declaring-accounts

**Comment by mhansen** [comment]
OK, seems reasonable (thanks for the real example!). I'd review a pull
request if you'd like to add this, with a test case.

**Comment by mhansen** [comment]
That sounds pretty hard. I don't know how to solve these problems. To be
honest I kinda just hacked this up with regular expressions, without being
too principled about it.

Negative lookbehind sounds expensive, I wouldn't be surprised if it wasn't
supported, sounds like the kind of regex that can quickly go
exponential-time. Instead, perhaps a positive-regex might work instead...
first match the "account " then inside that scope, add a match for
"foo:bar" accounts inside there. And make "account" have higher precedence
(somehow).

For accounts in a posting, they all start with spaces (maybe even at least
two spaces?) perhaps we could first look for the space, then dive into
matching an account.

**Comment by levitanong** [comment]
Hi, I just wanted to let you know that I'm still working on this, but I've been busy for the past week, and I'll likely only be able to make small progress next week.

I agree, negative lookbehind sounds expensive, and I hesitate to use it. I tried your approach a few days ago, but there doesn't seem to be much documentation about precedence or order of matching. I'm beginning to wonder if I should look into semantic highlighting, which would necessitate the creation of a language server.

**Comment by mhansen** [comment]
No worries, no rush, I haven’t really actively developed this lately so no
risk of merge conflicts :-)

I’ve never made a language server. I wonder how hard it would be. Probably
harder than JSON. I don’t know.

Maybe we could look at the hledger grammar and work from that? I think they
use some fancy haskell parser generator.

**Comment by yhoiseth** [comment]
For what it’s worth, I have a different use case for generalized account syntax: use languages other than English. 

(I prefer to keep my books in my native language, which is Norwegian. For example, _revenues_ is _inntekter_ in Norwegian.)

**Comment by mhansen** [comment]
Hi Yngve, internationalization is a pretty important use case that I hadn't
considered (my bad!). I'll update the syntax highlighter to be agnostic to
what you start your accounts with.

**Comment by mhansen** [comment]
Should be fixed now; give it a go and open a bug if you see any problems?

**Comment by yhoiseth** [comment]
Just updated, and it looks great so far. Thanks a ton :)

**Comment by levitanong** [comment]
Hurrah! Thanks for this!
